detectors:
  IrresponsibleModule:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  UtilityFunction:
    enabled: false
  MissingSafeMethod:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyConstants:
    enabled: false
  NilCheck:
    enabled: false

directories:
  'app/services/':
    TooManyInstanceVariables:
      enabled: false
    NilCheck:
      enabled: false
    DuplicateMethodCall:
      enabled: false
  'app/controllers/':
    TooManyStatements:
      enabled: false

exclude_paths:
  - db/
  - config/initializers/
  - spec/
  - 'app/controllers/coupons_controller.rb'
  - 'app/controllers/books_controller.rb'
