require: rubocop-rspec

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/admin/reviews.rb'
    - 'app/queries/**/*'
    - 'spec/**/*'

Documentation:
  Enabled: false

NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'ActiveAdmin.register']
  Exclude:
    - 'app/models/order.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'app/uploaders/**/*'

Style/UnneededInterpolation:
  Exclude:
    - 'app/views/orders/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/coupons_controller.rb'
    - 'app/presenters/catalog_presenter.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/services/checkout/form_variables_service.rb'

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
