require: rubocop-rspec

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/admin/reviews.rb'

Documentation:
  Enabled: false

NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'ActiveAdmin.register']

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'app/uploaders/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/coupons_controller.rb'

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
